// VoiceFlow C API - Auto-generated by cbindgen

#ifndef VOICEFLOW_H
#define VOICEFLOW_H

/* Warning: this file was auto-generated by cbindgen. Don't modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque handle to the VoiceFlow pipeline
 */
typedef struct VoiceFlowHandle VoiceFlowHandle;

/**
 * Result struct returned to foreign callers
 */
typedef struct VoiceFlowResult {
  bool success;
  char *formatted_text;
  char *raw_transcript;
  char *error_message;
  uint64_t transcription_ms;
  uint64_t llm_ms;
  uint64_t total_ms;
} VoiceFlowResult;

/**
 * Model info struct for FFI
 */
typedef struct ModelInfo {
  char *id;
  char *display_name;
  char *filename;
  float size_gb;
  bool is_downloaded;
} ModelInfo;

/**
 * Moonshine model info struct for FFI
 */
typedef struct MoonshineModelInfo {
  char *id;
  char *display_name;
  uint32_t size_mb;
  bool is_downloaded;
} MoonshineModelInfo;

/**
 * Initialize the VoiceFlow pipeline
 *
 * # Safety
 * config_path must be a valid null-terminated string or null for default
 */
struct VoiceFlowHandle *voiceflow_init(const char *configPath);

/**
 * Process audio samples and return formatted text
 *
 * # Safety
 * - handle must be a valid pointer from voiceflow_init
 * - audio_data must point to audio_len floats (16kHz mono PCM)
 * - context can be null
 */
struct VoiceFlowResult voiceflow_process(struct VoiceFlowHandle *handle,
                                         const float *audioData,
                                         uintptr_t audioLen,
                                         const char *context);

/**
 * Free a VoiceFlowResult's strings
 *
 * # Safety
 * Only call this once per result
 */
void voiceflow_free_result(struct VoiceFlowResult result);

/**
 * Cleanup and free the handle
 *
 * # Safety
 * Only call this once per handle
 */
void voiceflow_destroy(struct VoiceFlowHandle *handle);

/**
 * Get the library version
 */
const char *voiceflow_version(void);

/**
 * Get the models directory path
 */
char *voiceflow_models_dir(void);

/**
 * Get the number of available models
 */
uintptr_t voiceflow_model_count(void);

/**
 * Get model info by index
 *
 * # Safety
 * index must be < voiceflow_model_count()
 */
struct ModelInfo voiceflow_model_info(uintptr_t index);

/**
 * Free model info strings
 *
 * # Safety
 * Only call once per ModelInfo
 */
void voiceflow_free_model_info(struct ModelInfo info);

/**
 * Free a C string returned by other functions
 *
 * # Safety
 * Only call once per string
 */
void voiceflow_free_string(char *s);

/**
 * Get the current model ID from config
 */
char *voiceflow_current_model(void);

/**
 * Set the current model in config (requires restart to take effect)
 *
 * # Safety
 * model_id must be a valid null-terminated string
 */
bool voiceflow_set_model(const char *modelId);

/**
 * Get the HuggingFace download URL for a model
 *
 * # Safety
 * model_id must be a valid null-terminated string
 */
char *voiceflow_model_download_url(const char *modelId);

/**
 * Get the current STT engine ("whisper" or "moonshine")
 */
char *voiceflow_current_stt_engine(void);

/**
 * Set the current STT engine ("whisper" or "moonshine")
 *
 * # Safety
 * engine_id must be a valid null-terminated string
 */
bool voiceflow_set_stt_engine(const char *engineId);

/**
 * Get the current Moonshine model ("tiny" or "base")
 */
char *voiceflow_current_moonshine_model(void);

/**
 * Set the current Moonshine model ("tiny" or "base")
 *
 * # Safety
 * model_id must be a valid null-terminated string
 */
bool voiceflow_set_moonshine_model(const char *modelId);

/**
 * Get the number of available Moonshine models
 */
uintptr_t voiceflow_moonshine_model_count(void);

/**
 * Get Moonshine model info by index
 *
 * # Safety
 * index must be < voiceflow_moonshine_model_count()
 */
struct MoonshineModelInfo voiceflow_moonshine_model_info(uintptr_t index);

/**
 * Free Moonshine model info strings
 *
 * # Safety
 * Only call once per MoonshineModelInfo
 */
void voiceflow_free_moonshine_model_info(struct MoonshineModelInfo info);

/**
 * Check if a Moonshine model is downloaded
 *
 * # Safety
 * model_id must be a valid null-terminated string ("tiny" or "base")
 */
bool voiceflow_moonshine_model_downloaded(const char *modelId);

/**
 * Get the Moonshine models directory path
 */
char *voiceflow_moonshine_models_dir(void);

#endif  /* VOICEFLOW_H */
